name: Update awesome list

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Generate awesome list
        run: bash scripts/generate.sh
        env:
          GH_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Commit changes
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ secrets.USER_EMAIL }}"
          git add README.md data.json
          git diff --staged --quiet || git commit -m "chore(updates): updated entries in files"
          git push
