name: Update awesome list

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Awesome generator
        uses: simonecorsi/mawesome@v2
        with:
          template-path: "template/README.ejs"
          api-token: ${{ secrets.API_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          github-name: ${{ github.repository_owner }}
